### PR TITLE
Regex parsing instead of konan (should fix #228)

### LINKED ISSUE #228: Use regex for fast parsing import statement
The bundler needs to know all required statements of a particular module before executing it.

Currently, I'm using konan which uses babylon (babel's parser) under the hood. This is really slow for large file (react.js, react-dom) and could freeze the thread for several seconds.

I will move this script to a worker thread later for address the UI responsiness. But in the mean time, I would prefer using a faster way of parsing require statements.

Relevant code:

https://github.com/Sketch-sh/sketch-sh/blob/598839aa67c4414b4439936457bbb6e723dbb026/client/src/container/Container_require_collector.rei#L1

Reference implementation:

https://github.com/facebook/jest/blob/master/packages/jest-haste-map/src/lib/dependencyExtractor.ts#L55-L61

### PR DESCRIPTION
**Pull request by tatchi**
Here's my attempt to fix #228. The code is heavily inspired from the Jest repo (see link in the issue)

I don't really know how to test it extensively but at least the demo code works.

As discussed on discord with @thangngoc89, I implemented it in two ways:

* One that mimics what Jest does but which use an "unsafe" method.
* Another one that should be "safer".

We decided to go for the first option but I still commented out the second one if needed in the future. 

Don't hesitate if you have any suggestions.

### CODE REVIEW

**Comment by thangngoc89** [comment]
@tatchi Hey, could you recheck this PR? Currently it's throwing 

"SyntaxError: invalid regexp group"

on https://sketch-git-fork-tatchi-regex-parsing.sketch-sh.now.sh

**Comment by tatchi** [comment]
Hmm... Didn't get this error (with Chrome). I tested with firefox then and indeed I also have this error

**Comment by thangngoc89** [comment]
Same for me as well, Chrome works ok but not Firefox

**Comment by tatchi** [comment]
@thangngoc89 should be fixed (hopefully)

**Comment by thangngoc89** [comment]
Thank you. !

**Pull request merged**
