### PR TITLE
 fix: Refmt restore deleted block when called

### PR DESCRIPTION
**Pull request by thangngoc89**
Cloes #168

### CODE REVIEW

**Comment by thangngoc89** [comment]
cc @fstiffo  could you please try with this : https://rtop-cuxhsdhpng.now.sh/ to confirm ?

**Comment by fstiffo** [comment]
Now it not happens


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
09/04/18,
3:11:14 PM

**Comment by thangngoc89** [comment]
@fstiffo so it's fixed right ?

**Comment by fstiffo** [comment]
The problem never presented again! Thx

**Pull request merged**
