### PR TITLE
Auto hide large evaluated result

### LINKED ISSUE #118: Auto-hide large structures better, or allow manual hiding
When a large structure gets printed it can take up many screens without ever getting truncated with an ellipsis anywhere:

https://sketch.sh/s/LhrKjlqGtCDdDyBi0qZWL1/

screenshot_2018-08-20 buffer deque - sketch sh

### PR DESCRIPTION
**Pull request by thangngoc89**
This will auto hide structures that's more than 10 lines. 

Closes #118

### CODE REVIEW

**Comment by kyldvs** [comment]
Huge improvement, thank you!

A few suggestions:

1. The text `<truncated...>` does not match the font of the output so looks a bit weird
2. Might make sense for text to be more like: "(click to see more output)"
3. 10 lines still seems like a lot to me, but I understand if the output is less than 10 lines you would probably want to display it all. My suggestion would be to have behavior: `if(lines > 10) { display 5 lines } else { display all lines }`

**Comment by thangngoc89** [comment]
@kyldvs Thank you for your suggestions, I'll work on these improvements soon

**Comment by Drup** [comment]
Alternative implementation technique (which might be more complicated, I don't know): The toplevel has a mechanism to avoid printing values that are too deep/big. The depth is controlled by setting `Toploop.max_printer_depth` (default 100) and `Toploop.max_printer_step` (default 300) . If it goes above that; the printer prints "...". 

This way, even if the value is very big, you can still print the first few layers. If the user asks for it, you can then change the two values to big integers, and print it again.

**Comment by thangngoc89** [comment]
@Drup ah, that is an interesting information. I'll look into that

**Pull request merged**
