### PR TITLE
Migrate to jsx3 at once

### PR DESCRIPTION
**Pull request by jchavarri**
This is another approach to jsx3 migration, where all application is migrated at once. The advantage is that there's no need to create Jsx2 intermediate conversions.

After all components are migrated, we can run the app, find bugs and fix them.

~Full list (`find . -iregex '.*\(re\)' -not -path "./node_modules/*"`):~ Edit: actually we only need to migrate modules that use `statelessComponent` or `reducerComponent`. Here is the list:

- [x] shared/ReactContentLoader.re
- [x] src/App.re
- [x] src/Auth.re
- [x] src/AuthStatus.re
- [x] src/Home.re
- [x] src/Logout.re
- [x] src/Note.re
- [x] src/NoteNew.re
- [x] src/NoteTemplateChoose.re
- [x] src/NotFound.re
- [x] src/Router.re
- [x]  src/Shortcut.re
- [x] src/User.re
- [x] src/compat/ReLoadable.re
- [x] src/components/FontFaceObserver.re
- [x] src/components/Layout_WithTopbar.re
- [x] src/components/Logo.re
- [x] src/components/UI_Balloon.re
- [x] src/components/UI_DateTime.re
- [x] src/components/UI_DotFlashing.re
- [x] src/components/UI_FullpageLoading.re
- [x] src/components/UI_LoadingWrapper.re
- [x] src/components/UI_NoSketches.re
- [x] src/components/UI_SketchList.re
- [x] src/components/UI_SketchOwnerInfo.re
- [x] src/components/UI_Topbar.re
- [x] src/components/UI_TopbarUserInfo.re
- [x] src/components/UI_UserInfo.re
- [ ] src_editor/Editor_Blocks.re
- [x] src_editor/Editor_CodeBlock.re
- [ ] src_editor/Editor_Links.re
- [x] src_editor/Editor_Note_ForkButton.re
- [x] src_editor/Editor_Note_GetUserInfo.re
- [x] src_editor/Editor_NotePlaceholder.re
- [x] src_editor/Editor_Note_SaveButton.re
- [x] src_editor/Editor_Note.re
- [x] src_editor/Editor_TextBlock.re
- [x] src_embed/Embed.re

### CODE REVIEW

**Comment by andrii-antiukhov** [comment]
In this files i made changes, but not all was refactored to JSX3 (need to do this)
client/shared/ButterToast.re
client/shared/Fi.re
client/shared/React.re
client/shared/ReactOld.re
client/src/Note.re
client/src/Router.re
client/src/Router.rei
client/src/Shortcut.re
client/src/components/FontFaceObserver.re
client/src/components/Layout_WithTopbar.re
client/src/components/UI_DateTime.re
client/src/components/UI_NoSketches.re
client/src/components/UI_SketchList.re
client/src/components/UI_SketchOwnerInfo.re
client/src/components/UI_Topbar.re
client/src_editor/Editor_Blocks.re
client/src_editor/Editor_Blocks.rei
client/src_editor/Editor_Links.re
client/src_editor/Editor_Note.re
client/src_editor/Editor_Note_ForkButton.re
client/src_editor/Editor_Note_SaveButton.re
client/src_embed/Embed.re

**Comment by jchavarri** [comment]
@maxlibin @andrii-antiukhov I updated the list in the description as it was including many modules that were not React components, now it shows all modules that use either `statelessComponent` or `reducerComponent`. Only 29 to go!  💪

**Comment by jchavarri** [comment]
Updated the list with migrations in #331.

**Comment by jchavarri** [comment]
ftr, updated the branch with `develop` and merged #339 into it as well (thanks @maxlibin and @andrii-antiukhov for all the work!). I updated the list of components in description to reflect latest state, seems there are only a few left, I will try to pick some commits from #322 from @andrii-antiukhov and bring them to this branch.

Another thing missing will be updating reason-apollo lib, as the version we use is not compatible with jsx3. It seems we should be fine with 0.16.3: https://github.com/apollographql/reason-apollo/pull/195#commitcomment-33838912.

**Comment by maxlibin** [comment]
@jchavarri as far as I see both: [src/compat/ReLoadable.re](https://github.com/Sketch-sh/sketch-sh/pull/321/files#diff-21b03996fcf628035a3e7ff2481a849488dce85ffa65d51a7f20dcd3f49c5b59) and [src_embed/Embed.re](https://github.com/Sketch-sh/sketch-sh/pull/321/files#diff-133265fb260a43a79352ba47c406ee31508f3bfeec13ca267fe69c8f9afe3794) should be done?

**Comment by andrii-antiukhov** [comment]
@jchavarri Yes, can take this 2 files 
```
 src_editor/Editor_Blocks.re
 src_editor/Editor_Links.re
```
from my branch https://github.com/Sketch-sh/sketch-sh/pull/322 but need add a bit more changes because i did not know how correct finish refactoring in this file `src_editor/Editor_Blocks.re` Most of code refactored except code in comment like `TODO for refactor to JSX3`

**Comment by jchavarri** [comment]
- avatar image doesn't show when logged

- error after logging in
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in AuthStatus$IsAuthenticated (created by NoteNew)
    in NoteNew (created by ReLoadable$WithRender)
    in ReLoadable$WithRender (created by NoteNewLazy)
    in NoteNewLazy (created by AuthStatus$IsAuthenticated)

- error when saving: pop up appears twice

- error when saving:
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in Editor_Note$Editor_Note (created by Shortcut$Consumer)
    in Shortcut$Consumer (created by Editor_Note$WithShortcut)
    in Editor_Note$WithShortcut (created by AuthStatus$IsAuthenticated)

**Pull request merged**
